### ISSUE TITLE
Docker部署支持

### ISSUE THREAD

**Issue by dameng324** [lizongying/my-tv-server#1]
建议发布时添加docker镜像的生成

**Comment by lizongying** [comment]
可以是可以，只是没必要。
直接下载可执行文件，执行就行了。
因为配置只需要执行一次就可以，用本地
服务再合适不过了，隐私性还能保证。

倒是可以在服务器上，把服务发布到公网上。
我加上吧，也许有人会这么用。

**Comment by dameng324** [comment]
电视端如果只需要配置一次,下次启动时自动加载上次配置取到的结果,不用docker部署倒也还好, 看大佬的时间吧  不是很关紧.

**Comment by lizongying** [comment]
已支持docker

[ghcr.io](https://github.com/lizongying/my-tv-server/pkgs/container/my-tv-server)
[hub.docker.com](https://hub.docker.com/r/lizongying/my-tv-server)
