### ISSUE TITLE
检测到病毒？

### ISSUE THREAD

**Issue by kamkdd** [lizongying/my-tv-server#10]
我win11电脑下载检查到病毒？
![图片1](https://github.com/lizongying/my-tv-server/assets/146134472/a9ee976b-e561-4ab7-b8b3-21a11febf6d1)
![图片2](https://github.com/lizongying/my-tv-server/assets/146134472/ff35e734-cf47-42d2-9676-5e6eda65e640)

**Comment by kamkdd** [comment]
![Uploading PixPin_2024-05-01_18-42-44.png…]()

**Comment by kamkdd** [comment]
![PixPin_2024-05-01_18-42-44](https://github.com/lizongying/my-tv-server/assets/146134472/3b1bb89c-e144-4e65-ad86-9f2dc3ba362c)

**Comment by lizongying** [comment]
1. 請在本倉庫內下載。
2. 所有源代碼請自行檢查
