### ISSUE TITLE
软路由的docker 布置不了，出现下述错误提示。

### ISSUE THREAD

**Issue by kevinandlee** [lizongying/my-tv-server#11]
![012](https://github.com/lizongying/my-tv-server/assets/66158553/9b992129-6bbe-4c67-8963-f9341eec5bb9)

**Comment by lizongying** [comment]
不建議在docker中使用。
本來就是一個很簡單的東西，在docker中還得映射端口，更麻煩。
另外，這個基本是用完就可以關閉的。

我在mac arm64 的docker中是沒問題的。
