### ISSUE TITLE
小白求指教

### ISSUE THREAD

**Issue by kevinandlee** [lizongying/my-tv-server#9]
docker pull lizongying/my-tv-server
能不能给一个一键 拉取创建容器的指令。谢谢。

**Comment by lizongying** [comment]
就是一個簡單的web服務
docker pull ghcr.io/lizongying/my-tv-server:v1.0.7 && docker run -d -p 8000:8000 ghcr.io/lizongying/my-tv-server:v1.0.7 
不過這裡有個問題，要把局域網地址替換一下，用192*替換172*
直接訪問
http://192*:8000/mytv/index.html

**Comment by kevinandlee** [comment]
您好，我在软路由 docker 里面运行，故障日志是这样，不知道如何修改。谢谢
[image: 012.jpg]
